# Generated by Django 5.2.17 on 2026-09-21 15:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0002_claimfeedback"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="claimfeedback",
            constraint=models.UniqueConstraint(
                fields=("user", "claim"), name="unique_user_claim_feedback"
            ),
        ),
    ]
