# Generated by Django 5.2.17 on 2026-09-24 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_claimfeedback_unique_user_claim_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['submitted_at'], name='claim_submitted_at_idx'),
        ),
    ]
