# Generated by Django 5.2.17 on 2026-09-24 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_claim_claim_submitted_at_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='text',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(2000)]),
        ),
    ]
