# Generated by Django 5.2.17 on 2026-10-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0006_claim_valid_claim_text_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
