# Generated by Django 5.2.17 on 2026-10-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_alter_analysis_credibility_score_and_more'),
        ('claims', '0006_claim_valid_claim_text_length'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='analysis',
            name='valid_verdict_values',
        ),
        migrations.AddConstraint(
            model_name='analysis',
            constraint=models.CheckConstraint(condition=models.Q(('verdict__in', ['CREDIBLE', 'UNCERTAIN', 'MISINFORMATION']), ('verdict__isnull', True), _connector='OR'), name='valid_verdict_values'),
        ),
        migrations.AddConstraint(
            model_name='analysis',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('model_confidence__gte', 0.0), ('model_confidence__lte', 1.0)), ('model_confidence__isnull', True), _connector='OR'), name='valid_model_confidence_range'),
        ),
    ]
